# fly.toml file generated for pokemon-hex-generator on 2022-11-11T03:19:34-05:00

app = "pokemon-hex-generator"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "pleebz/pokemon-hex-generator:1.20.0"

[env]
  PORT = "5001"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
