const configTypes = {
  m_JP_EU_US: 'uint8_t',
  m_firstFossilTopSlot: 'bool',
  m_secondFossilTopSlot: 'bool',
  m_timesBeforeSR: 'int',
  m_autoSoftReset: 'bool',
  m_internetTime: 'uint16_t',
  m_skip3Days: 'bool',
  m_unsafeDC: 'bool',
  m_useLinkCode: 'bool',
  m_useRandomCode: 'bool',
  m_seed: 'uint8_t',
  m_linkCode: 'uint8_t',
  m_waitTime: 'uint8_t',
  m_addFriends: 'bool',
  m_profile: 'uint8_t',
  m_alternate: 'bool',
  m_dayToSkip: 'unsigned long',
  m_saveAt: 'uint16_t',
  m_boxCount: 'int',
  m_boxesToTrade: 'uint8_t',
  m_completeDex: 'bool',
  m_day: 'uint8_t',
  m_month: 'uint8_t',
  m_year: 'int',
  m_maxCycle: 'int',
  m_eggStepGroup: 'uint8_t',
  m_columnsOfEggs: 'uint8_t',
  m_deleteCount: 'unsigned int',
  m_addFriend: 'bool',
  m_titleScreenBuffer: 'bool',
};

module.exports = {
  configTypes,
};
